  version: '3.8'

  services:
    db:
      image: postgres:latest
      container_name: 0755c55427b7
      environment:
        POSTGRES_USER: myuser
        POSTGRES_PASSWORD: mypassword
        POSTGRES_DB: mydatabase
      ports:
        - "5434:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
#    redis:
#      image: redis:latest
#      ports:
#        - "6379:6379"
  volumes:
    postgres_data:

#version: '3.8'
#
#services:
#  postgres:
#    image: postgres:15
#    restart: always
#    environment:
#      POSTGRES_USER: myuser
#      POSTGRES_PASSWORD: mypassword
#      POSTGRES_DB: mydatabase
#    ports:
#      - "5434:5432"
#
#  app:
#    build: .
#    depends_on:
#      - postgres
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5434/mydatabase
#      SPRING_DATASOURCE_USERNAME: myuser
#      SPRING_DATASOURCE_PASSWORD: mypassword
#      # Настройки для Redis (при необходимости)
#      SPRING_REDIS_HOST: redis
#      SPRING_REDIS_PORT: 6379
#      SPRING_REDIS_DATABASE: 0
#
#  redis:
#    image: redis:latest
#    restart: always
#    ports:
#      - "6379:6379"